mysqlVersion: "5.7"
redisVersion: "3.2"
cassandraVersion: "2.2"
elasticSearchVersion: "2.4"
loadTest: false
useIngress: false
gui: false

image:
  account: gengstrand
  feed: "15"
  version: "1.0"
  local: true
